### ISSUE TITLE
Появляется ошибка Uncaught ReferenceError: showForm is not defined

### ISSUE THREAD

**Issue by potter062** [floor12/yii2-module-mailing#1]
```
Вот строка в которой ошибка
`</ul><a class="btn btn-sm btn-success btn-mailing-add" onclick="showForm(&quot;/adminpanel/mailing/mailing/form&quot;,0)"><i class="fa fa-plus"></i> создать рассылку</a><form id="w0" class="table-mailing-autosubmit" action="/adminpanel/mailing/mailing" method="GET" data-container="#items">`
Никак не получается исправить
```

**Comment by potter062** [comment]
Решено. 
В MailingAsset
 public $depends = [
        'yii\bootstrap\BootstrapAsset',
        'yii\web\JqueryAsset'
    ];
заменить на
public $depends = [
        'yii\bootstrap\BootstrapAsset',
        'yii\web\JqueryAsset',
		'floor12\editmodal\EditModalAsset'
    ];

**Comment by floor12** [comment]
Да, showForm это js функция из моего модуля для редактирования объектов в модальном окне, он ругался на нее из-за того что ассет не подгружен. Надо прописать в базовый ассет модуля рассылки зависимость от ассета EditModal. Я эту багу не заметил так как у меня этот ассет во всех проектах по дефолту подгружен.
