### ISSUE TITLE
Help yii2-queue!

### ISSUE THREAD

**Issue by potter062** [floor12/yii2-module-mailing#2]
Подскажите пожалуйста в какой контроллер в вашем модуле вставить этот код 
$id = Yii::$app->queue->delay(15 * 60)->push(new WriteJob([
			'text' => 'Отправка рассылки',
			'file' => Yii::$app->basePath . '/runtime/file.txt'
		]));
Всё чего я добился так это изменение статуса на Отправляется. Если запускаю команду ./yii mailing/queue то отправляется всё сразу. Кучу информации перерыл но пока безрезультатно. А так модуль работает отлично как в описании.

**Comment by floor12** [comment]
я так понял что у тебя проблема в том, что ты хочешь отправлять письма не всей рассылкой, а с паузами? Допустим по 100 писем раз в минуту или типа того?
Ты объясни какую именно проблему ты хочешь решить, и, вероятно, я подскажу какое-то другое решение которое подойдет для этого модуля.

**Comment by potter062** [comment]
Да именно так что бы письма отправлялись не все сразу а с периодичностью. Может я зря заморачиваюсь но многие пишут что такая рассылка нежелательна.

**Comment by floor12** [comment]
Я никаких проблем с рассылкой писем пачками до 10 тысяч штук не встречал с моим модулем. В самом модуле в письмах вроде бы все заголовки стоят нормальные. Главное, чтобы письма не попали в спам и хорошо принимались всеми серверами - надо не забыть прописать spf запиись в днс домена, от имени которого хочешь слать письма и IP сервера откуда шлешь. Если в редких случаях письма попадают в спам - то это обычно дело в самом контенте или заголовке письма.

**Comment by floor12** [comment]
Да, письма я рассылаю во всех проектах через стандартный почтовый агент exim, установленный локально на сервере с сайтом. Хоть и существует мнение, что настроить его тяжело, у меня как-то все по дефолту и письма ходят на ура!

**Comment by potter062** [comment]
Понял спасибо за совет так и поступлю. Да Жень а можно email или как ещё можно связаться.
Я самоучка и бывает нужен просто совет. Я на этой неделе буду отдавать людям сайт хотелось бы знать твоё мнение хоть правильно делаю или нет может укажешь на ошибки. Хочу поменять профессию. А то вождение грузовика немного надоело. Меня Саша зовут мой  email potter062@gmail.com
